### ISSUE TITLE
Convert to NOAA Data FTP Access?

### ISSUE THREAD

**Issue by rdustinb** [rdustinb/noaasolarweather#21]
I discovered multiple repositories of NOAA's data sets that are available via FTP that also include historical data sets for multiple years in the past. An example of the FTP data is here:

ftp://ftp.swpc.noaa.gov/pub/lists/ace/

There are four "real-time" data files in this folder as this folder contains ALL ACE data. NOAA also produces historical data files, see the README in the FTP folders.

**Comment by rdustinb** [comment]
More consistent data sets available here:

ftp://ftp.swpc.noaa.gov/pub/lists/

**Comment by arnoldmashava** [comment]
There are data accessibility issues, via both http and ftp connections. Not that it's a bug in the code but just the NOAA servers just don't want anyone to access them...

**Comment by rdustinb** [comment]
Thanks arnoldmashava, yes one thing I've found is that accessing NOAA's server directly have major accessibility issues. Unless they open up the data sources to where others can store data for fallback reasons, I am not sure how to improve reliability.

**Comment by rdustinb** [comment]
The reliability issues seem to have been fixed on the NOAA server side and this enhancement is not planned to be implemented anymore.

**Comment by arnoldmashava** [comment]
Heartfeltly acknowledged @rdustinb - the lapse of time, from [then](https://github.com/rdustinb/noaasolarweather/issues/21#issuecomment-156242399) when there still existed the `ftp` data accessibility issue, to the [present](https://github.com/rdustinb/noaasolarweather/issues/21#issuecomment-2442332499) when all has been resolved, really feels like the progression of a clock from an alternate Universe, with a different methodology of quantifying years and months. 

As a predictor variable, time is indeed a very elusive phenomenon.

In maintaining and updating this [noaasolarweather](https://github.com/rdustinb/noaasolarweather) codebase, thank you so much, for the seemingly infinite fortitude and capacity to evolve, in catching up with the hyper-paced rapidity with which the [Python Source Releases](https://www.python.org/downloads/source/) keep rolling and one always has to calibrate their act in unison with Computational Modernity.

Yes, thankfully everything has been resolved from the side of the NOAA Server, therefore, this brings finality and closure to this [Issue](https://github.com/rdustinb/noaasolarweather/issues/21).

Expressed in a rather convoluted manner, herewith the gratitude from @arnoldmashava:

```dart
>_ sudo ¡Muchas Gracias! --verbosity=debug
```

Rastafari.
